version: '3.7'

services:
  mysql:
    container_name: adm_business_mysql
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=business
    security_opt:
      - seccomp:unconfined
    ports:
      - 3306:3306
    networks:
      - adm_business_network

  zookeeper:
    container_name: adm_business_zookeeper
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - 2181:2181
    networks:
      - adm_business_network

  kafka:
    container_name: adm_business_kafka
    image: wurstmeister/kafka:latest
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    ports:
      - 9094:9094
    networks:
      - adm_business_network

  kafkadrop:
    container_name: kafkadrop
    image: obsidiandynamics/kafdrop:latest
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
    ports:
      - 9000:9000
    networks:
      - adm_business_network

networks:
  adm_business_network: